version: '3.9'

volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME}

services:
  flappy-alby:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - ${FLAPPY_ALBY_EXTERNAL_PORT-5000}:${FLAPPY_ALBY_INTERNAL_PORT-80}

  postgres:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT-5432}:${POSTGRES_PORT-5432}
    volumes:
      - postgres_data:/var/lib/postgresql