version: '3.9'

configs:
  grafana_config:
    file: ./infrastructure/grafana/grafana.ini
  grafana_datasources_config:
    file: ./infrastructure/grafana/provisioning/datasources/datasources.yml
  loki_config:
    file: ./infrastructure/loki/loki-config.yml
  prometheus_config:
    file: ./infrastructure/prometheus/prometheus-config.yml
  prometheus_alert_rules_config:
    file: ./infrastructure/prometheus/alert-rules.yml
  alert-manager_config:
    file: ./infrastructure/alert-manager/alert-manager-config.yml

volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME}
  grafana_data:
    name: ${GRAFANA_VOLUME}
  loki_data:
    name: ${LOKI_VOLUME}
  node-exporter_data:
    name: ${NODE_EXPORTER_VOLUME}
  prometheus_data:
    name: ${PROMETHEUS_VOLUME}
  alert-manager_data:
    name: ${ALERT_MANAGER_VOLUME}

services:
  flappy-alby:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - ${FLAPPY_ALBY_EXTERNAL_PORT-5000}:${FLAPPY_ALBY_INTERNAL_PORT-80}

  postgres:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT-5432}:${POSTGRES_PORT-5432}
    volumes:
      - postgres_data:/var/lib/postgresql
  
  grafana:
    ports:
      - ${GRAFANA_PORT-3000}:${GRAFANA_PORT-3000}
    #    configs:
    #      - source: grafana_config
    #        target: /etc/grafana/grafana.ini
    #      - source: grafana_datasources_config
    #        target: /etc/grafana/provisioning/datasources/datasources.yml
    volumes:
      - grafana_data:/var/lib/grafana                                                                                             # Storage Grafana's data
      - ./infrastructure/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml   # Move to configuration
      - ./infrastructure/grafana/grafana.ini:/etc/grafana/grafana.ini                                                             # Move to configuration                             
      - ./infrastructure/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards                                     # Initialize Grafana dashboards  
  loki:
    ports:
      - ${LOKI_PORT-3100}:${LOKI_PORT-3100}
    #    configs:
    #      - source: loki_config
    #        target: /mnt/config/loki-config.yml
    command: -config.file=/mnt/config/loki-config.yml
    volumes:
      - loki_data:/data/loki
      - ./infrastructure/loki/loki-config.yml:/mnt/config/loki-config.yml                                                         # Move to configuration 
  
  prometheus:
    ports:
      - ${PROMETHEUS_PORT-9090}:${PROMETHEUS_PORT-9090}
    volumes:
      - prometheus_data:/prometheus
      - ./infrastructure/prometheus/prometheus-config.yml:/mnt/config/prometheus-config.yml                                         # Move to configuration
      - ./infrastructure/prometheus/alert-rules.yml:/mnt/config/alert-rules.yml                                                     # Move to configuration
    #    configs:
    #      - source: prometheus_config
    #        target: /mnt/config/prometheus-config.yml
    #      - source: prometheus_alert_rules_config
    #        target: /mnt/config/alert-rules.yml
    command:
      - '--config.file=/mnt/config/prometheus-config.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
  
  alert-manager:
    ports:
      - ${ALERTMANAGER_PORT-9093}:${ALERT_MANAGER_PORT-9093}
    volumes:
      - alert-manager_data:/data
      - ./infrastructure/alert-manager/alert-manager-config.yml:/mnt/config/alert-manager-config.yml                               # Move to configuration
    command: --config.file=/mnt/config/alert-manager-config.yml --log.level=debug
    #    configs:
    #      - source: alert-manager_config
    #      - source: alert-manager_config
    #        target: /mnt/config/alert-manager-config.yml
  
  node-exporter:
    ports:
      - ${NODE_EXPORTER_PORT-9100}:${NODE_EXPORTER_PORT-9100}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  
  postgres-exporter:
    ports:
      - ${POSTGRES_EXPORTER_PORT-9187}:${POSTGRES_EXPORTER_PORT-9187}
    environment:
      DATA_SOURCE_NAME: ${DATA_SOURCE_NAME}