# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Loki
    orgId: 1
  - name: Prometheus
    orgId: 2

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: "Loki"
    id:	1
    uid: "hlk52w-nk"
    orgId: 1
    type: "loki"
    typeName: "Loki"
    access:	"proxy"
    url: "loki:3100"
    password:	""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData: {}
    readOnly: false
    
  - name: Prometheus
    type: prometheus
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        # Field with internal link pointing to data source in Grafana.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        - datasourceUid: my_jaeger_uid
          name: traceID

        # Field with external link.
        - name: traceID
          url: 'http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D'