# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Loki
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: "Loki"
    id:	1
    uid: "hlk52w-nk"
    orgId: 1
    type: "loki"
    typeName: "Loki"
    access:	"proxy"
    url: "loki:3100"
    password:	""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData: {}
    readOnly: false
    