global:
  scrape_interval: 15s

rule_files:
  - ./alert-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ "alert-manager:9093" ]

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: "loki"
    scrape_interval: 5s
    static_configs:
      - targets: [ "loki:3100" ]

  - job_name: "grafana"
    scrape_interval: 5s
    static_configs:
      - targets: [ "grafana:3000" ]

  - job_name: "node"
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: postgres-exporter
    static_configs:
      - targets: [ "postgres-exporter:9187" ]

  - job_name: flappy-alby
    static_configs:
      - targets: [ "flappy-alby:80" ]

  - job_name: alert-manager
    static_configs:
      - targets: [ "alert-manager:9093" ]
