name: CI-PROD

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
      - '!*alpha*'
      - '!*beta*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      # QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      # Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Meta
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: |
            docker.io/${{ github.repository }}
          tags: |
            type=sha
            type=pep440,pattern={{version}}
            type=ref,event=pr
          labels: |
            maintainer= ${{ github.author }}
            org.opencontainers.image.description=The Flappy-Alby game!
            org.opencontainers.image.vendor=AlbyCorp
          flavor: |
            latest=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            
      # Dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./FlappyAlby.API/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm/v7